.github/workflows/build.yml, src/testproject/helpers/reporthelper.py, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/remote.py
PyPI doesn't support standard "git describe" versions.
Construct a version string from using the latest TAG and
the number of commits since that tag.
Also add step for automatic publishing to PyPI on releases.
Signed-off-by: Vitaly Bukhovsky <vitaly@testproject.io>
=> Change SDK version format

README.rst
=> Add 'coming soon' notice for Appium support.

README.rst, tests/examples/simple/web_test.py
=> Updated simple web example in examples and docs.

src/testproject/sdk/internal/agent/agent_client.py
=> Fixed issue with incorrect developer token used when reporting.

.github/workflows/build.yml
=> Added pre-publishing twine check on .rst validity

README.rst
=> Changed all links to anonymous hyperlinks to allow duplicate targets.

src/testproject/sdk/drivers/webdriver/safari.py
=> Added desired capabilities to Safari to allow proper session creation.

src/testproject/helpers/sockethelper.py, src/testproject/sdk/exceptions/__init__.py, src/testproject/sdk/exceptions/agentconnectexception.py, src/testproject/sdk/exceptions/invalidtokenexception.py, src/testproject/sdk/exceptions/obsoleteversionexception.py, src/testproject/sdk/internal/agent/agent_client.py
=> Aligned Agent connect error handling with Java SDK implementation

tests/examples/drivers/android/android_driver_chrome_test.py, tests/examples/drivers/android/android_driver_test.py
=> Disable keyboard opening in Android examples

HISTORY.md
=> Added changes for 0.63.15 to HISTORY.md

HISTORY.md
=> Updated history to reflect latest changes as of version 0.63.18

.github/workflows/build.yml
=> Update CI syntax to let builds run again.

HISTORY.md
This PR updates the history log in preparation for releasing SDK version 0.63.19
=> Updated HISTORY.md to include changes preparing for 0.63.19

HISTORY.md
=> Updated HISTORY.md to include changes preparing for 0.64.0

HISTORY.md
Signed-off-by: Marat Strelets <marat@testproject.io>
=> Updated HISTORY.md to include changes preparing for 0.64.1

README.rst
=> Add missing line break for code-block highlighting in README file

setup.py
=> Explicitly stating which appium-python-client version to use.

src/testproject/decorator/report_assertion_errors.py
Before this change the SDK was not parsing the AssertionError message before report the assertion failure, it looked something like this:
This change should parse the AssertionError message so that the TestProject platform Reports will show them more beautified.
=> #68 - Parse assertion errors to show them properly show on platform Reports.

src/testproject/helpers/addonhelper.py, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/generic.py, src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/internal/agent/agent_client.py, src/testproject/sdk/internal/helpers/custom_appium_command_executor.py, src/testproject/sdk/internal/helpers/custom_command_executor.py, src/testproject/sdk/internal/helpers/generic_command_executor.py, src/testproject/sdk/internal/helpers/reporting_command_executor.py, tests/examples/drivers/generic_driver_test.py
=> Fixing addon execution to handle given StepSettings (timeout, sleep and invert result).

src/testproject/classes/step_settings.py, src/testproject/helpers/step_helper.py, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/chrome.py, src/testproject/sdk/drivers/webdriver/edge.py, src/testproject/sdk/drivers/webdriver/firefox.py, src/testproject/sdk/drivers/webdriver/ie.py, src/testproject/sdk/drivers/webdriver/safari.py, tests/ci/headless/chrome_addon_proxy_test.py, tests/ci/headless/chrome_basic_test.py, tests/ci/headless/chrome_multiple_test.py, tests/ci/headless/chrome_no_options_or_caps_test.py, tests/ci/headless/chrome_step_settings_test.py, tests/ci/headless/cloud_basic_test.py, tests/ci/headless/firefox_basic_test.py, tests/examples/drivers/web/chrome_driver_test.py, tests/examples/drivers/web/edge_driver_test.py, tests/examples/drivers/web/firefox_driver_test.py, tests/examples/drivers/web/ie_driver_test.py, tests/examples/drivers/web/safari_driver_test.py, tests/examples/reports/report_failed_pytest_assertion_test.py, tests/examples/reports/report_failed_unittest_assertion_test.py, tests/internal/addon_invert_result_test.py, tests/internal/addon_step_settings_test.py, tests/internal/report_decorator_test.py
**Added**
- New settings (AlwaysPass failure behavior) - 'always_pass'.
- Screenshot behavior handling method.
- Step result (invert/always_pass) handling method.
**Changed**
- Edited internal test to test all step settings.
- Handle sleep method is now static and added a default value of None to the 'command' argument of the method.
- Renamed attributes (to be readable with underscores)
=> Improve Step Settings and Step Helper classes.

src/testproject/rest/messages/drivercommandreport.py, src/testproject/rest/messages/stepreport.py, src/testproject/sdk/internal/reporter/reporter.py, tests/ci/unittests/rest/messages/drivercommandreport_test.py, tests/ci/unittests/rest/messages/stepreport_test.py
Adding more attributes to these classes (implemented and taken into consideration also on Agent) allows to create more detailed manual and automatic step reporting.
=> Improve reporting classes

HISTORY.md, README.rst, setup.py
Update the link in the documentation and change the package url
=> Rename the repo from python-sdk to python-opensdk

src/testproject/classes/driver_step_settings.py, src/testproject/classes/step_settings.py, src/testproject/enums/findbytype.py, src/testproject/helpers/addonhelper.py, src/testproject/sdk/internal/agent/agent_client.py
Previously Addon step execution was reported by the Agent and caused a lack of information in the report and sometimes wrong reports.
Addon reporting is now done manually by the SDK and takes into consideration all the StepSettings applied to the driver.
=> Improve addon reporting - handle step settings (screenshot, failure behavior, invert result and more)

src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/generic.py, src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/internal/helpers/reporting_command_executor.py
This function is a gap that doesn't exists in the driver and should be implemented for easy access from the driver instance.
=> Adding 'pause' execution action step to driver classes.

src/testproject/decorator/behave_reporter.py, src/testproject/enums/environmentvariable.py, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/generic.py, src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/internal/agent/agent_client.py, tests/examples/frameworks/behave/features/environment.py
Update the job name during runtime if the job name is left blank during driver initialization.
=> Update job name of Behave test during runtime.

HISTORY.md, README.rst
=> Updating README and HISTORY - Version Bump.

src/testproject/helpers/seleniumhelper.py
Fixes #142 .
set is not JSON serializable, which causes issues when sending the execute request.
=> Creating addon locator of XPATH mistakenly returned set instead of dict.

src/testproject/sdk/internal/helpers/reporting_command_executor.py
=> Fixing driver action 'pause'

HISTORY.md
=> Updating version from 0.65.2 to 0.65.3

HISTORY.md, src/testproject/helpers/seleniumhelper.py
Added support for Accessibility ID and IOS Predicate for mobile addon executions.
Fix for Issue #151 
=> Added support for Mobile locators on addon execution

HISTORY.md, src/testproject/decorator/behave_reporter.py
Implementing the changes requested here https://github.com/testproject-io/python-opensdk/pull/141#discussion_r604921038
=> Simplifying Behave Reporter code format to make it more readable

HISTORY.md
=> version bump, history updated.

HISTORY.md, README.rst, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/chrome.py, src/testproject/sdk/drivers/webdriver/edge.py, src/testproject/sdk/drivers/webdriver/firefox.py, src/testproject/sdk/drivers/webdriver/generic.py, src/testproject/sdk/drivers/webdriver/ie.py, src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/drivers/webdriver/safari.py, src/testproject/sdk/internal/agent/agent_client.py
Added Agent URL parameter which controls the address of the Agent.
=> Add agent url parameter to driver constructors

README.rst, src/testproject/decorator/behave_reporter.py, src/testproject/decorator/pytestBDD_reporter.py, src/testproject/helpers/activesessionhelper.py, src/testproject/helpers/confighelper.py, src/testproject/rest/messages/sessionresponse.py, src/testproject/sdk/internal/agent/agent_client.py
Added logging of report URL for applicable test execution
=> Feat: Add Remote execution support

README.rst, src/testproject/rest/messages/sessionrequest.py, src/testproject/rest/reportsettings.py, src/testproject/sdk/drivers/webdriver/base/basedriver.py, src/testproject/sdk/drivers/webdriver/chrome.py, src/testproject/sdk/drivers/webdriver/edge.py, src/testproject/sdk/drivers/webdriver/firefox.py, src/testproject/sdk/drivers/webdriver/generic.py, src/testproject/sdk/drivers/webdriver/ie.py, src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/drivers/webdriver/safari.py, tests/ci/unittests/rest/messages/sessionrequest_test.py
Added logic which allows the control of report name and report path
=> Feat: Control reports configuration

src/testproject/sdk/drivers/webdriver/remote.py, src/testproject/sdk/internal/helpers/reporting_command_executor.py
This PR addresses issue: https://github.com/testproject-io/python-opensdk/issues/168
=> Fix: Avoid reporting step if test report is disabled

src/testproject/rest/messages/sessionresponse.py, src/testproject/sdk/internal/agent/agent_client.py, src/testproject/tcp/socketmanager.py
This PR adds a check if the agent is connected to the SDK on agent version 2.3.0 or greater
=> Validate agent connection

HISTORY.md
=> Chore: update 1.2.0 relesae date

src/testproject/rest/messages/sessionresponse.py, src/testproject/sdk/internal/agent/agent_client.py
Signed-off-by: Artem Kuznetsov <artem.kuznetsov@testproject.io>
=> Add ability to receive and log warnings from the Agent.

HISTORY.md
Signed-off-by: David Goichman <david.goichman@testproject.io>
=> Version bump to 1.2.1

src/testproject/sdk/internal/helpers/custom_command_executor.py
Relates to this issue: #180 
Signed-off-by: Artem Kuznetsov <artem.kuznetsov@testproject.io>
=> fix: expose w3c to selenium as a class member

HISTORY.md
Signed-off-by: oriddd <ori.dafna@testproject.io>
=> chore: version bump.

README.rst
Add BrowserStack driver creation example.
Signed-off-by: oriddd <ori.dafna@testproject.io>
=> docs: update Cloud integration readme.
