- .github/workflows/build.yml
- setup.py
- src/testproject/definitions.py
1. Check in metadata (for regular SDK users)
2. Check in TP_SDK_VERSION environment variable (for building purposes)
If both are not detected, an SdkException is thrown.
> Improvement for determining the version number

- src/testproject/sdk/internal/helpers/custom_command_executor.py
> Only report tests that have been properly identified as a test.

- .github/workflows/build.yml
Create a separate step for checking the validity of the
distribution package, to detect any issues as part of PR builds
and not only after merging to the master branch.
Signed-off-by: Vitaly Bukhovsky <vitaly@testproject.io>
> CI: Always check distribution package

- src/testproject/helpers/reporthelper.py
- src/testproject/sdk/internal/helpers/reporting_command_executor.py
This is a fix for issue #11. Added detection of unittest `tearDown` and `tearDownClass` methods so that actions in there get reported to the test they belong to instead of separately.
> Added unittest teardown detection for correct test reporting.

- .github/workflows/build.yml
- HISTORY.md
- README.rst
- src/testproject/sdk/internal/helpers/custom_appium_command_executor.py
- src/testproject/sdk/internal/helpers/custom_command_executor.py
- src/testproject/sdk/internal/helpers/reporting_command_executor.py
- tests/ci/headless/cloud_basic_test.py
If cloud:URL is capability set, Agent (0.63.11+) will attempt to initialize a driver using provided URL of a cloud provider such as BrowserStack or SauceLabs.
> Custom capability 'cloud:URL' documentation and CI test

- setup.py
This PR adds `packaging` as a dependency, which is used to determine whether the current Agent version supports the use of a generic (non-UI) driver.
> Add 'packaging' as a dependency

- .github/workflows/build.yml
Add Python 3.9 to the Python version matrix.
Tests and PyPI steps will now use Python 3.9.
> Add Python 3.9 to CI Matrix

- setup.py
This PR allows for Appium-Python-Client versions >= 1.0.1 to be installed as a dependency when the SDK is installed (this was fixed to 1.0.1)
> Allow latest version of Appium to be installed with SDK

- src/testproject/decorator/report_assertion_errors.py
When screenshot is True, the assertion error report will take a screenshot.
> Adding optional 'screenshot' argument to the decorator.

- src/testproject/executionresults/operationresult.py
- src/testproject/sdk/internal/agent/agent_client.py
**Previously** the SDK would ignore the response body coming back from the Agent.
Ignoring the body is fine only if the body is empty.
**Now** the SDK will use the response and will raise a more generic exception with the response's message.
When there is no response body or message, it will show a more generic message in the exception.
> Issue 89 - Handling response messages coming back from the Agent on response 404.

- src/testproject/decorator/report.py
- src/testproject/helpers/reporthelper.py
- src/testproject/rest/messages/sessionrequest.py
- src/testproject/rest/reportsettings.py
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- src/testproject/sdk/drivers/webdriver/generic.py
- src/testproject/sdk/drivers/webdriver/remote.py
- src/testproject/sdk/internal/agent/agent_client.py
- src/testproject/sdk/internal/helpers/reporting_command_executor.py
**Previously** the decorator would just set the report settings as ENV variables, but that wouldn't work in all cases (Assuming it was tested before and worked for some cases).
**Now** the decorator will not only set the ENV variables, it will also explicitly change the attributes needed for the report to be reported with the intended functionality.
> Issue 101 - Fixing 'report' decorator.

- src/testproject/decorator/report.py
- src/testproject/rest/reportsettings.py
- src/testproject/sdk/internal/agent/agent_client.py
- tests/internal/report_decorator_test.py
- Added unit-test for internal use to test the report decorator's uploaded reports.
- Reverted previous change since it didn't help with the [issue](https://github.com/testproject-io/python-sdk/issues/48) the user was complaining about.
However I've added the option to set test name even when using pytest.fixture.
> Report decorator fixes

- HISTORY.md
- README.rst
- src/testproject/decorator/behave_reporter.py
- src/testproject/decorator/report_assertion_errors.py
- src/testproject/enums/environmentvariable.py
- src/testproject/helpers/activesessionhelper.py
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- src/testproject/sdk/drivers/webdriver/remote.py
- tests/ci/headless/firefox_basic_test.py
- tests/examples/frameworks/behave/features/environment.py
- tests/examples/frameworks/behave/features/selenium_test.feature
- tests/examples/frameworks/behave/features/steps/step_definitions.py
- tests/pageobjects/web/profile_page.py
Added support for Behave Framework BDD reporting.
Users will need to use the decorator on the method they create the driver from.
As the driver can also be created in a fixture or any other method, I am not checking where before hooks for
driver creation.
After step and after scenario will construct the report for TestProject platform.
The user can insert his driver regularly into the Behave context, they will just need to use the report_behave decorator on the after_step and after_scenario hooks to enable the reporing into the platform.
Step failures will show the exception + error message.
> Behave Reporting Support

- src/testproject/sdk/internal/agent/agent_client.py
- src/testproject/tcp/socketmanager.py
This behavior of closing the socket too soon would cause the Agent to go out of DevelopmentState and will cause the step reporting to be responded with 417.
> Fixing unwanted socket closure before reporting thread is finished.

- src/testproject/helpers/addonhelper.py
- src/testproject/helpers/step_helper.py
- src/testproject/sdk/internal/helpers/custom_appium_command_executor.py
- src/testproject/sdk/internal/helpers/custom_command_executor.py
- src/testproject/sdk/internal/helpers/reporting_command_executor.py
Adding this attribute to the class instead of passing this attribute to the handle_timeout method for every call on the method.
> Adding class attribute 'session_id' to the StepHelper class - Fixes handle_timeout method.

- src/testproject/classes/__init__.py
- src/testproject/classes/web_driver_wait.py
- tests/ci/headless/chrome_web_driver_wait_test.py
- tests/examples/web_driver_wait/web_driver_wait_test.py
- tests/internal/web_driver_wait_test.py
The example shows all the information the user needs in order to use the SDK's WebDriverWait instead of Selenium's WebDriverWait class.
The SDK's WebDriverWait wraps Selenium's WebDriverWait class just like a decorator wraps a function.
It takes into consideration all StepSettings applied on the driver.
In addition, it knows how to silently execute the same methods by disabling automatic reporting in the driver.
After a silent execution, it takes the method's result, infers all the execution information (fields, expected condition method name and the method used by the WebDriverWait) and reports it manually according to the result of the WebDriverWait.
**Previously**, the result of the step got reported automatically by the driver in accordance to the success of the driver command.
This …
> Adding SDK class WebDriverWait to support proper reporting of expected conditions applied to it.

- src/testproject/classes/web_driver_wait.py
fix: creating 'passed' parameter to the reporting result.
- The 'result' that is returned might not always be a boolean, in fact, if a result has returned it means that the wait didn't end with timeout exception and the step probably passed.
- 'result' should be used to create a boolean named 'passed' for the reporting.
- The original 'result' should still be returned.
> Fixing reporting from TestProjectWebDriverWait when the returned result is not a boolean. 

- src/testproject/decorator/behave_reporter.py
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- src/testproject/sdk/drivers/webdriver/generic.py
- src/testproject/sdk/drivers/webdriver/remote.py
The get_active_driver_instance method raises an SDK exception if no client is initialized, avoid an exception
while attempting to update the job name if no client has been initialized yet.
This happens in cases such as using the behave_reporter decorator on a before_scenario hook, where there is a context attribute 
with an active feature running, but the driver has not been initialized yet before attempting to update a job name.
> Avoid SdkException if no active driver while attempting to initialize agent client

- src/testproject/sdk/internal/agent/agent_client.py
This is done to prevent an iteration over a NoneType.
Closing #144 
> Avoid iterating NoneType when addon execution response's 'fields' key is None.

- HISTORY.md
- README.rst
- src/testproject/enums/report_type.py
- src/testproject/enums/reportnamingelement.py
- src/testproject/rest/messages/sessionrequest.py
- src/testproject/rest/messages/sessionresponse.py
- src/testproject/rest/reportsettings.py
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- src/testproject/sdk/drivers/webdriver/chrome.py
- src/testproject/sdk/drivers/webdriver/edge.py
- src/testproject/sdk/drivers/webdriver/firefox.py
- src/testproject/sdk/drivers/webdriver/generic.py
- src/testproject/sdk/drivers/webdriver/ie.py
- src/testproject/sdk/drivers/webdriver/remote.py
- src/testproject/sdk/drivers/webdriver/safari.py
- src/testproject/sdk/internal/agent/agent_client.py
- tests/ci/unittests/rest/messages/drivercommandreport_test.py
- tests/ci/unittests/rest/messages/sessionrequest_test.py
- tests/internal/cloud_local_reporting_test.py
When a local report is not supported - SDK will output:
Target Agent version [2.0.0] doesn't support local reports. Upgrade the Agent to the latest version and try again.
When local cloud is requested but Agent is offline, SDK will output:
Agent responded with status 412: [Agent is offline and is not able to upload the execution report to the cloud as requested]
> Allow controlling report type - local / cloud or both

- .github/workflows/build.yml
For external PRs (forks) run only the linting and offline pipelines.
Signed-off-by: Vitaly Bukhovsky <vitaly@testproject.io>
> Skip the build-test-publish job for ext prs

- src/testproject/decorator/pytestBDD_reporter.py
- tests/examples/frameworks/pytest-bdd/conftest.py
- tests/examples/frameworks/pytest-bdd/features/selenium_test.feature
- tests/examples/frameworks/pytest-bdd/steps/test_testproject.py
To enable the following functions have to be annotated in conftest.py:
@pytestBDD_reporter()
def pytest_bdd_after_step(request, feature, scenario, step, step_func,step_func_args):
pass
@pytestBDD_reporter()
def pytest_bdd_after_scenario(request, feature, scenario):
pass
@pytestBDD_reporter()
def pytest_bdd_step_error(request, feature, scenario, step, step_func, step_func_args, exception):
pass
@pytestBDD_reporter()
def pytest_bdd_before_scenario(request, feature, scenario):
pass
Signed-off-by: bbornhau <79279609+bbornhau@users.noreply.github.com>
> decorator to enable gherkin style reporting when using pytest_bdd

- HISTORY.md
- src/testproject/sdk/internal/agent/agent_client.py
- src/testproject/sdk/internal/agent/agent_client_singleton.py
Fix for the agent session reuse, tests with the same Job and Project name will be aggregated under the same Report.
> Fix  agent session reuse logic

- HISTORY.md
- src/testproject/helpers/reporthelper.py
If tests were in a class, the class name was reported instead.
If the test class was in the root folder, the inferred project name was <testclass>.p
This is a fix for https://github.com/testproject-io/python-opensdk/issues/160
> Avoid reporting Class name if tests resides inside a Class with a pytest fixture

- src/testproject/definitions.py
- src/testproject/sdk/internal/agent/agent_client.py
- src/testproject/tcp/socketmanager.py
Changed the validation of agent connection on agents 2.3.0 or greater to check if UUID is not empty instead of comparing versions.
> Feat: Agent connection check

- src/testproject/sdk/internal/helpers/redact_helper.py
Signed-off-by: David Goichman <david.goichman@testproject.io>
> Avoid nonetype error when checking if element is an Android password element

- .github/ci/docker-compose.yml
- src/testproject/rest/messages/customtestreport.py
- src/testproject/rest/messages/drivercommandreport.py
- src/testproject/rest/messages/reportitemtype.py
- src/testproject/rest/messages/stepreport.py
- src/testproject/sdk/internal/agent/agent_client.py
- src/testproject/sdk/internal/agent/reports_queue.py
- src/testproject/sdk/internal/agent/reports_queue_batch.py
- tests/ci/unittests/rest/messages/customtestreport_test.py
- tests/ci/unittests/rest/messages/drivercommandreport_test.py
- tests/ci/unittests/rest/messages/stepreport_test.py
Adding logic to support reporting at batches due to issue #179 
ReportsQueue class was added and methods related to the reports queue were extracted from AgentClient class.
ReportsQueueBatch was added to support up to 10 reports in a batch.
Logic added to AgentClient - to support the new ReportsQueue from agent version: 3.0.0
> feat: Allow reporting steps at batches from OpenSDK.

- HISTORY.md
- src/testproject/helpers/confighelper.py
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- tests/ci/unittests/helpers/confighelper_test.py
This related to this issue: #181 
Signed-off-by: Artem Kuznetsov <artem.kuznetsov@testproject.io>
> fix: check if token is in driver constructor before raising SdkException

- .github/ci/docker-compose.yml
- src/testproject/sdk/internal/agent/reports_queue.py
As part of the development of the #179 feature.
We've found that we are not retrying to send the reports in case of a failure while sending reports. 
This logic was added to the csharp-sdk and java-sdk. 
Adding this logic also to python-sdk.
Signed-off-by: oriddd <ori.dafna@testproject.io>
> feat: retry send reports in case of failure

- .github/ci/docker-compose.yml
- src/testproject/sdk/drivers/webdriver/base/basedriver.py
- src/testproject/sdk/drivers/webdriver/chrome.py
- src/testproject/sdk/drivers/webdriver/edge.py
- src/testproject/sdk/drivers/webdriver/firefox.py
- src/testproject/sdk/drivers/webdriver/generic.py
- src/testproject/sdk/drivers/webdriver/ie.py
- src/testproject/sdk/drivers/webdriver/remote.py
- src/testproject/sdk/drivers/webdriver/safari.py
- src/testproject/sdk/internal/agent/agent_client.py
Let the user configure the timeout of the connection with the agent (in milliseconds)
> fix: make connection timeout with the agent configurable
